# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnotateBackgroundJobStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("finished", "finished")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("args", jsonfield.fields.JSONField()),
                ("scores", jsonfield.fields.JSONField()),
                ("info", jsonfield.fields.JSONField()),
            ],
        )
    ]
