name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python via conda.
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Install the cadd-scripts package from bioconda
        run: conda install -c bioconda -y cadd-scripts==1.6.1

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install project Python dependencies
        run: |
          pip install -r requirements/test.txt
      - name: Run tests
        run: |
          coverage run --rcfile=.coveragerc manage.py test -v 2 --settings=config.settings.test
          coverage xml
          coverage report
      - name: Check formatting
        run: make black arg=--check
      - name: Run Codacy coverage reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
